### ISSUE TITLE
Feature Request: x509v3 Subject Alt. Name - URI 

### ISSUE THREAD

**Issue by ghost** [digitalbazaar/opencred-idp#1]
x509v3 subjectAltName URI Issuing
I believe a WebID is simply a URI [1].  Therefore, the capacity to issue a WebID-TLS 'styled' x509 Cert seems reasonable. 

Would like to see the method issue a certificate embedding the credential URI.

Compatibility might also be considered with RWW Applications seeking AUTH. I will put this into the 'cloud storage compatibility' feature request note.

[1] http://lists.w3.org/Archives/Public/public-webid/2014Jun/0009.html

**Comment by ghost** [comment]
Also: i think if such a function be supported; perhaps the x509 cert should be issued as a device credential, which can be linked to the online credential (with a passphrase).

**Comment by dlongley** [comment]
Closing to archive repo.
