### ISSUE TITLE
Cloud Storage Compatibility

### ISSUE THREAD

**Issue by ghost** [digitalbazaar/opencred-idp#2]
As Addressed by TimBL's Design Notes [1][2], which have been very well progressed through Andrei Sambra's [3] works, inclusive of related implementations [4][5], the ability to issue a cloud-storage location - and perhaps the capacity to identify 'persona' as described by FQDN's linked to FOAF (and related) documents; should provide a bridge between the core identity document; and, functional 'persona' documents as may be used by RWW Applications that may in-turn have some form of web-payments related functionality. 

A good example of how this might work; could be the use of a microblogging[6] service, linked to webcredits[7], for the purposes of providing a pre-defined reward for hitting the 'like' or 'share' button of a microblog-post. 

(sometimes finding a good link can save an enormous amount of time and/or provide other benefit).

It seems functionally beneficial to support the WebID-TLS method; whilst perhaps additionally supporting the selection of a session based profile document; such as a FOAF file otherwise used in a variety of RWW applications...

[1] http://www.w3.org/DesignIssues/CloudStorage.html
[2] http://www.w3.org/DesignIssues/ReadWriteLinkedData.html
[3] http://myprofile-project.org/thesis/manuscript_en.pdf
[4] http://data.fm/
[5] http://rww.io/
[6] http://cimba.co/
[7] http://webcredits.org/

**Comment by dlongley** [comment]
Closing to archive repo.
